Repository yg-park/EOF_SeparateTrashCollection, pull requests merged in 2023-12, with the labels that each got.

#9 feature: [ANN] data_augmentation 수행 코드 파일 추가
  ArtificialNeuralNetwork/data_augmentation.ipynb
Labels: 기능 추가

#18 feature: [CLIENT] Comm 클래스 개발
  ArtificialNeuralNetwork/model.py
  EOF_TRASH_CLIENT/gpio.py
  EOF_TRASH_CLIENT/image.jpg
  EOF_TRASH_CLIENT/picam.py
  EOF_TRASH_CLIENT/tcp_client.py
  EOF_TRASH_CLIENT/udp_client.py
Labels: 기능 추가

#23 doc: 인텔에서 가이드한 README.md 초안 작성
  Documents/Design/high_level_design.png
  Documents/EOF_presentation.pptx
  Documents/project 일정.xlsx
  README.md
Labels: 도큐먼트

#27 [Client/Server] python venv requirements.txt 수정 - 권강현
  .gitignore
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/appdirs-1.4.4-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/certifi-2020.6.20-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/chardet-4.0.0-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/colorama-0.4.4-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/contextlib2-0.6.0.post1-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/distlib-0.3.1-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/distro-1.5.0-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/html5lib-1.1-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/idna-2.10-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/ipaddr-2.2.0-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/msgpack-1.0.0-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/packaging-20.9-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/pep517-0.9.1-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/pip-20.3.4-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/progress-1.5-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/pyparsing-2.4.7-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/requests-2.25.1-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/setuptools-44.1.1-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/six-1.16.0-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/toml-0.10.1-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/urllib3-1.26.5-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/webencodings-0.5.1-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/.clent_venv/share/python-wheels/wheel-0.34.2-py2.py3-none-any.whl
  EOF_TRASH_CLIENT/requirements.txt
  EOF_TRASH_SERVER/requirements.txt
Labels: 리팩토링
