Repository yg-park/EOF_SeparateTrashCollection, pull requests merged in 2024-01, with the labels that each got.

#35 [Client] 클라이언트 스크래치 코드 프레임워크 작성 - 박도현
  EOF_TRASH_CLIENT/ setup.sh
  EOF_TRASH_CLIENT/Comm/communication.py
  EOF_TRASH_CLIENT/deprecated/communication.py
  EOF_TRASH_CLIENT/deprecated/tcp_client.py
  EOF_TRASH_CLIENT/deprecated/udp_client.py
  EOF_TRASH_CLIENT/lane_control.py
  EOF_TRASH_CLIENT/main.py
Labels: 기능 추가

#36 [Server] 서버 스크래치 코드 프레임워크 작성 - 박도현
  EOF_TRASH_SERVER/Comm/image_comm.py
  EOF_TRASH_SERVER/GUI.py
  EOF_TRASH_SERVER/main.py
  EOF_TRASH_SERVER/multi_thread.py
  EOF_TRASH_SERVER/requirements.txt
Labels: 기능 추가

#38 [Client/Server] 프레임 끊어지는 문제 해결 - 우창민
  EOF_TRASH_SERVER/Comm/communication.py
  EOF_TRASH_SERVER/Comm/image_comm.py
  EOF_TRASH_SERVER/PyQt_framework/GUI.py
  EOF_TRASH_SERVER/PyQt_framework/rcv_img_thread.py
  EOF_TRASH_SERVER/main.py
  EOF_TRASH_SERVER/multi_thread.py
Labels: 리팩토링, 기능 업데이트

#39 [Server] 코드 수정 및 리팩토링 - 박도현
  EOF_TRASH_SERVER/Comm/communication.py
  EOF_TRASH_SERVER/Comm/image_comm.py
  EOF_TRASH_SERVER/Comm/string_comm.py
  EOF_TRASH_SERVER/Comm/voice_comm.py
  EOF_TRASH_SERVER/PyQt_framework/GUI.py
  EOF_TRASH_SERVER/PyQt_framework/rcv_img_thread.py
  EOF_TRASH_SERVER/deprecated/PyQt5_GUI.py
  EOF_TRASH_SERVER/deprecated/communication_all_in_one.py
  EOF_TRASH_SERVER/deprecated/main.py
  EOF_TRASH_SERVER/main.py
Labels: 리팩토링

#42 [Server] 서버측 오디오 수신 추가 - 우창민
  EOF_TRASH_SERVER/Comm/audio_comm.py
  EOF_TRASH_SERVER/Comm/voice_comm.py
  EOF_TRASH_SERVER/PyQt_framework/GUI.py
  EOF_TRASH_SERVER/PyQt_framework/rcv_audio_thread.py
Labels: 기능 추가

#43 [Client]클라이언트 측 웹캠입력 오디오 녹음 및 전송 구현 - 우창민
  EOF_TRASH_CLIENT/Comm/send_audio.py
  EOF_TRASH_CLIENT/GPIO_HW_control/rc_servo_motor.py
  EOF_TRASH_CLIENT/audio/result.mp3
  EOF_TRASH_CLIENT/audio/voice_record.py
  EOF_TRASH_CLIENT/lane_control.py
Labels: 기능 추가

#44 [Client] 클라이언트측 문자열 수신 및 수신 데이터에 따른 HW 제어 추가
  EOF_TRASH_CLIENT/Comm/rcv_string.py
  EOF_TRASH_CLIENT/lane_control.py
  EOF_TRASH_CLIENT/network/communication.py
  EOF_TRASH_CLIENT/network/tcp_client.py
  EOF_TRASH_CLIENT/network/udp_client.py
Labels: 기능 추가

#45 [Server] 서버측 문자열 송신 기능 구현
  EOF_TRASH_SERVER/Comm/string_comm.py
  EOF_TRASH_SERVER/PyQt_framework/GUI.py
Labels: 기능 추가

#46 [Client] HW 버튼 제어 기능 디바운싱 포함 추가 및 오디오 녹음 및 전송 파트 버튼 눌릴 때 작동하도록 변경
  EOF_TRASH_CLIENT/GPIO_HW_control/button.py
  EOF_TRASH_CLIENT/lane_control.py
Labels: 기능 추가

#53 [Server]서버 GUI 틀 변경
  EOF_TRASH_SERVER/PyQt_framework/GUI.py
Labels: 기능 업데이트

#55 [Client]클라이언트 측 lcd 제어 기능 구현
  EOF_TRASH_CLIENT/Audio/voice_record.py
  EOF_TRASH_CLIENT/GPIO_HW_control/lcd.py
  EOF_TRASH_CLIENT/audio/output.wav
  EOF_TRASH_CLIENT/lane_control.py
  EOF_TRASH_CLIENT/requirements.txt
  EOF_TRASH_CLIENT/setup.sh
Labels: 기능 추가, 기능 업데이트

#56 [Client] 클라이언트 측 버튼 스레드 문제 해결
  EOF_TRASH_CLIENT/Audio/voice_record.py
  EOF_TRASH_CLIENT/Communication/audio_communication.py
  EOF_TRASH_CLIENT/lane_control.py
Labels: 버그 발견, 기능 업데이트

#63 [Server] object detection 후 classification으로 진입하는 동작 알고리즘 수정 - 권강현
  EOF_TRASH_SERVER/Comm/audio_comm.py
  EOF_TRASH_SERVER/Comm/image_comm.py
  EOF_TRASH_SERVER/Inference/glass_bottle_classifier.py
  EOF_TRASH_SERVER/Inference/glass_bottle_detector.py
  EOF_TRASH_SERVER/Inference/pet_bottle_detector.py
  EOF_TRASH_SERVER/PyQt_framework/GUI.py
  EOF_TRASH_SERVER/PyQt_framework/ROI_detect_classify_thread.py
  EOF_TRASH_SERVER/git_kgh.sh
  EOF_TRASH_SERVER/git_pdh.sh
  EOF_TRASH_SERVER/git_pyg.sh
  EOF_TRASH_SERVER/git_wcm.sh
  EOF_TRASH_SERVER/main.py
Labels: 리팩토링, 기능 업데이트

#64 [Client] git author switch shell script & Async 방식 적용-우창민
  EOF_TRASH_CLIENT/GPIO_HW_control/servo_motor.py
  EOF_TRASH_CLIENT/git_kgh.sh
  EOF_TRASH_CLIENT/git_pdh.sh
  EOF_TRASH_CLIENT/git_pyg.sh
  EOF_TRASH_CLIENT/git_wcm.sh
  EOF_TRASH_CLIENT/lane_control.py
  EOF_TRASH_CLIENT/setup.sh
Labels: 기능 추가, 기능 업데이트

#65 [Server] 모델 스위칭을 함수 호출 한번으로 가능하도록 model 클래스 수정 - 권강현
  EOF_TRASH_SERVER/Inference/bottle_classifier.py
  EOF_TRASH_SERVER/Inference/bottle_detector.py
  EOF_TRASH_SERVER/Inference/glass_bottle_classifier.py
  EOF_TRASH_SERVER/Inference/glass_bottle_detector.py
  EOF_TRASH_SERVER/Inference/otx_api.py
  EOF_TRASH_SERVER/Inference/pet_bottle_classifier.py
  EOF_TRASH_SERVER/Inference/pet_bottle_detector.py
  EOF_TRASH_SERVER/PyQt_framework/GUI.py
  EOF_TRASH_SERVER/PyQt_framework/ROI_detect_classify_thread.py
  EOF_TRASH_SERVER/requirements.txt
Labels: 리팩토링, 기능 업데이트

#68 [Server] 서버 디렉토리 구조 변경 && 코드 리팩토링
  EOF_TRASH_SERVER/_deprecated/audio_comm.py
  EOF_TRASH_SERVER/_deprecated/image_comm.py
  EOF_TRASH_SERVER/_deprecated/rcv_audio_thread copy.py
  EOF_TRASH_SERVER/_deprecated/rcv_img_thread copy.py
  EOF_TRASH_SERVER/main.py
  EOF_TRASH_SERVER/pyqtGUI/main_window.py
  EOF_TRASH_SERVER/pyqtGUI/threads/ROI_detect_classify_thread.py
  EOF_TRASH_SERVER/pyqtGUI/threads/rcv_audio_thread.py
  EOF_TRASH_SERVER/pyqtGUI/threads/rcv_img_thread.py
  EOF_TRASH_SERVER/resources/received_audio.wav
  EOF_TRASH_SERVER/utils/Comm/hw_control_comm.py
  EOF_TRASH_SERVER/utils/Comm/voice_inf_comm.py
  EOF_TRASH_SERVER/utils/Inference/bottle_classifier.py
  EOF_TRASH_SERVER/utils/Inference/bottle_detector.py
  EOF_TRASH_SERVER/utils/Inference/otx_api.py
  EOF_TRASH_SERVER/utils/Inference/voice_inference.py
Labels: 리팩토링

#69 [Model] Speech To Text용 모듈 openai-whisper를 추가 - 박용근
  EOF_TRASH_SERVER/Audio/received_sound.wav
  EOF_TRASH_SERVER/Audio/whisper.py
  EOF_TRASH_SERVER/Audio/whisper/__init__.py
  EOF_TRASH_SERVER/Audio/whisper/__main__.py
  EOF_TRASH_SERVER/Audio/whisper/assets/gpt2.tiktoken
  EOF_TRASH_SERVER/Audio/whisper/assets/mel_filters.npz
  EOF_TRASH_SERVER/Audio/whisper/assets/multilingual.tiktoken
  EOF_TRASH_SERVER/Audio/whisper/audio.py
  EOF_TRASH_SERVER/Audio/whisper/decoding.py
  EOF_TRASH_SERVER/Audio/whisper/model.py
  EOF_TRASH_SERVER/Audio/whisper/normalizers/__init__.py
  EOF_TRASH_SERVER/Audio/whisper/normalizers/basic.py
  EOF_TRASH_SERVER/Audio/whisper/normalizers/english.json
  EOF_TRASH_SERVER/Audio/whisper/normalizers/english.py
  EOF_TRASH_SERVER/Audio/whisper/timing.py
  EOF_TRASH_SERVER/Audio/whisper/tokenizer.py
  EOF_TRASH_SERVER/Audio/whisper/transcribe.py
  EOF_TRASH_SERVER/Audio/whisper/triton_ops.py
  EOF_TRASH_SERVER/Audio/whisper/utils.py
  EOF_TRASH_SERVER/Audio/whisper/version.py
  EOF_TRASH_SERVER/requirements.txt
Labels: 기능 추가

#71 [클라이언트] 버튼 입력 감지 방식을 폴링에서 인터럽트로 변경 - 권강현
  EOF_TRASH_CLIENT/GPIO_HW_control/lcd.py
  EOF_TRASH_CLIENT/GPIO_HW_control/rc_servo_motor.py
  EOF_TRASH_CLIENT/lane_control.py
  EOF_TRASH_CLIENT/main.py
Labels: 기능 업데이트

#72 [Server] 음성인식을 통한 모델 변경 기능 적용
  EOF_TRASH_SERVER/Audio/received_sound.wav
  EOF_TRASH_SERVER/Audio/whisper.py
  EOF_TRASH_SERVER/Audio/whisper/__init__.py
  EOF_TRASH_SERVER/Audio/whisper/__main__.py
  EOF_TRASH_SERVER/Audio/whisper/assets/gpt2.tiktoken
  EOF_TRASH_SERVER/Audio/whisper/assets/mel_filters.npz
  EOF_TRASH_SERVER/Audio/whisper/assets/multilingual.tiktoken
  EOF_TRASH_SERVER/Audio/whisper/audio.py
  EOF_TRASH_SERVER/Audio/whisper/decoding.py
  EOF_TRASH_SERVER/Audio/whisper/model.py
  EOF_TRASH_SERVER/Audio/whisper/normalizers/__init__.py
  EOF_TRASH_SERVER/Audio/whisper/normalizers/basic.py
  EOF_TRASH_SERVER/Audio/whisper/normalizers/english.json
  EOF_TRASH_SERVER/Audio/whisper/normalizers/english.py
  EOF_TRASH_SERVER/Audio/whisper/timing.py
  EOF_TRASH_SERVER/Audio/whisper/tokenizer.py
  EOF_TRASH_SERVER/Audio/whisper/transcribe.py
  EOF_TRASH_SERVER/Audio/whisper/triton_ops.py
  EOF_TRASH_SERVER/Audio/whisper/utils.py
  EOF_TRASH_SERVER/Audio/whisper/version.py
  EOF_TRASH_SERVER/pyqtGUI/main_window.py
  EOF_TRASH_SERVER/pyqtGUI/threads/ROI_detect_classify_thread.py
  EOF_TRASH_SERVER/pyqtGUI/threads/audio_processing_thread.py
  EOF_TRASH_SERVER/resources/received_audio.wav
Labels: 기능 추가

#73 [Server] GUI text 출력 부분 구현 - 우창민
  EOF_TRASH_SERVER/pyqtGUI/main_window.py
Labels: 도움 요청, 기능 업데이트

#75 [Server] GUI 출력 내용 수정- 우창민
  EOF_TRASH_SERVER/pyqtGUI/main_window.py
Labels: 리팩토링

#82 [client] 서버로부터 텍스트 명령을 받아 동작을 수행하는 로직 추가
  EOF_TRASH_CLIENT/Communication/hw_control_communication.py
  EOF_TRASH_CLIENT/lane_control.py
Labels: 기능 추가

#83 [server] 텍스트박스 명령어 입력 기능 추가
  EOF_TRASH_SERVER/pyqtGUI/main_window.py
Labels: 기능 추가

#84 [Client] "서버 프로그램의 원격 명령을 통한 클라이언트 프로그램 실행/종료" 시나리오에서 클라이언트 측 로직 추가
  Documents/my_service.service
  EOF_TRASH_CLIENT/Communication/audio_communication.py
  EOF_TRASH_CLIENT/Communication/hw_control_communication.py
  EOF_TRASH_CLIENT/Communication/image_communication.py
  EOF_TRASH_CLIENT/GPIO_HW_control/servo_motor.py
  EOF_TRASH_CLIENT/lane_control.py
  EOF_TRASH_CLIENT/launch_main.sh
  EOF_TRASH_CLIENT/listen_launch_cmd.py
  EOF_TRASH_CLIENT/resources/communication_config.ini
  EOF_TRASH_CLIENT/resources/gpio_config.ini
Labels: 기능 추가, 리팩토링, 기능 업데이트

#87 [Project Management] 프로젝트에 issue template, PR template을 적용합니다.
  .github/ISSUE_TEMPLATE/-client-server-model--여기에-제목을-적습니다.md
  .github/PR_TEMPLATE/-client-server-model--여기에-제목을-적습니다.md
Labels: 도큐먼트

#88 [Server] 서버측 메인 프로그램 실행 쉘스크립트 작성 & README 수정 & Design 폴더 내부 구조 수정
  Documents/Design/HW/HW_circuit.png
  Documents/Design/README_THUMB/program_icon.png
  Documents/Design/SW Class Diagram/작성 툴.txt
  Documents/Design/SW FLOW CHART/FLOW CHART 그리는 사이트.txt
  Documents/Design/SW Sequence Diagram/작성 툴-starUML.txt
  Documents/Design/SW/high_level_design.png
  Documents/Design/SW/작성 툴.txt
  Documents/Design/UI/GUI_MainFrame.png
  EOF_TRASH_CLIENT/README.md
  EOF_TRASH_SERVER/EOF:EOF.sh
  EOF_TRASH_SERVER/README.md
  EOF_TRASH_SERVER/git_wcm.sh
  EOF_TRASH_SERVER/resources/glass_bottle_classification/README.md
  EOF_TRASH_SERVER/resources/glass_bottle_detection/README.md
  EOF_TRASH_SERVER/resources/idle_frame.png
  EOF_TRASH_SERVER/resources/llama2/README.md
  EOF_TRASH_SERVER/resources/pet_bottle_classification/README.md
  EOF_TRASH_SERVER/resources/pet_bottle_detection/README.md
  EOF_TRASH_SERVER/resources/whisper/README.md
  README.md
Labels: 기능 업데이트

#89 [Client] LCD 오동작 수정, 모델 변경 시 스피커 출력 추가 - 우창민
  EOF_TRASH_CLIENT/lane_control.py
  EOF_TRASH_CLIENT/listen_launch_cmd.py
  EOF_TRASH_CLIENT/resources/communication_config.ini
  EOF_TRASH_CLIENT/resources/recorded_voice.wav
Labels: 기능 추가, 기능 업데이트

#90 [Server] SW UML 다이어그램 추가
  Documents/Design/SW/ClassDiagram/Classdiagram_Client.png
  Documents/Design/SW/ClassDiagram/Classdiagram_Server.png
  Documents/Design/SW/GanttChart/전체일정 _12월.png
  Documents/Design/SW/GanttChart/전체일정 _1월.png
  Documents/Design/SW/HighLevelDesign/high_level_design.png
  Documents/Design/SW/MileStone/마일스톤 _12월.png
  Documents/Design/SW/MileStone/마일스톤 _1월.png
  Documents/Design/SW/SequenceDiagram/서버측 이미지 수신 후 추론 및 HW제어.drawio
  Documents/Design/SW/SequenceDiagram/서버측 이미지 수신 후 추론 및 HW제어.png
  Documents/Design/SW/SequenceDiagram/서버측 클라이언트 원격 실행_종료.png
  Documents/Design/SW/SequenceDiagram/클라이언트측 녹음 후 라마를 통한 대답!.png
  Documents/Design/SW/작성 툴.txt
Labels: 도큐먼트

#93 [Document] AI MODEL README 위치 수정 및 Main README 수정 - 우창민
  Documents/Design/README_THUMB/project_ppt_thumbnail.png
  Documents/Design/SW/GanttChart/GanttChart_Dec.png
  Documents/Design/SW/GanttChart/GanttChart_JAN.png
  Documents/Design/SW/SequenceDiagram/Image_inferencing.png
  Documents/Design/SW/SequenceDiagram/remote_control.png
  Documents/Design/SW/SequenceDiagram/voice_control.png
  Documents/Model_README/GlassClassification_README.md
  Documents/Model_README/GlassDetection_README.md
  Documents/Model_README/LLAMA2_README.md
  Documents/Model_README/PetClassification_README.md
  Documents/Model_README/PetDetection_README.md
  Documents/Model_README/WHISPER_README.md
  EOF_TRASH_SERVER/resources/program_icon.png
  README.md
Labels: 도큐먼트

#94 [Model] 유리병 Detection 모델 핫픽스 + 시퀀스다이어그램 수정 - 박용근
  Documents/Design/SW/SequenceDiagram/EOF:EOF_sequence_diagram.drawio
  Documents/Design/SW/SequenceDiagram/Image_inferencing.png
  Documents/Design/SW/SequenceDiagram/[sequence]서버측 이미지 수신 후 추론 및 HW제어.png
  Documents/Design/SW/SequenceDiagram/[sequence]음성 인식 flow.png
  Documents/Design/SW/SequenceDiagram/[sequence]전체 동작 flow.png
  Documents/Design/SW/SequenceDiagram/[sequence]클라이언트측 녹음 후 라마를 통한 대답!.png
  Documents/Design/SW/SequenceDiagram/remote_control.png
  Documents/Design/SW/SequenceDiagram/voice_control.png
  Documents/Design/SW/SequenceDiagram/서버측 이미지 수신 후 추론 및 HW제어.drawio
  EOF_TRASH_SERVER/EOF:EOF.sh
  EOF_TRASH_SERVER/git_wcm.sh
  EOF_TRASH_SERVER/pyqtGUI/main_window.py
  EOF_TRASH_SERVER/resources/glass_bottle_detection/model/confidence_threshold
  EOF_TRASH_SERVER/resources/glass_bottle_detection/model/config.json
  EOF_TRASH_SERVER/resources/glass_bottle_detection/model/label_schema.json
  EOF_TRASH_SERVER/resources/glass_bottle_detection/model/model.xml
  EOF_TRASH_SERVER/resources/glass_bottle_detection/template/configuration.yaml
  EOF_TRASH_SERVER/resources/glass_bottle_detection/template/template.yaml
  EOF_TRASH_SERVER/utils/Inference/bottle_detector.py
Labels: 기능 업데이트

#96 [Document] README 수정
  README.md
Labels: 도큐먼트

#99 [Document] README conflict Fix
  Documents/Design/HW/HW_Appearance_back.jpg
  Documents/Design/HW/HW_Appearance_front.jpg
  Documents/Design/README_THUMB/video_thumbnail.png
  Documents/Design/UI/ProgramLaunchICon.png
  EOF_TRASH_CLIENT/README.md
  EOF_TRASH_SERVER/README.md
  README.md
Labels: 도큐먼트

#101 [Documents] README 수정(개발명세서 제외 최종)
  Documents/Design/SW/GanttChart/GanttChart.png
  Documents/Design/SW/GanttChart/GanttChart_Dec.png
  Documents/Design/SW/GanttChart/GanttChart_JAN.png
  Documents/Design/UI/GUI_RUNNING.png
  EOF_TRASH_CLIENT/README.md
  EOF_TRASH_SERVER/README.md
  README.md
Labels: 도큐먼트
